/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_demo_jni_JNISecurity */

#ifndef _Included_com_android_demo_jni_JNISecurity
#define _Included_com_android_demo_jni_JNISecurity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_demo_jni_JNISecurity
 * Method:    Encrypt
 * Signature: ([B[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_android_demo_jni_JNISecurity_Encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_android_demo_jni_JNISecurity
 * Method:    Decrypt
 * Signature: ([B[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_android_demo_jni_JNISecurity_Decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_android_demo_jni_JNISecurity
 * Method:    getDefaultPartner
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_android_demo_jni_JNISecurity_getDefaultPartner
  (JNIEnv *, jclass);

/*
 * Class:     com_android_demo_jni_JNISecurity
 * Method:    getDefaultSeller
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_android_demo_jni_JNISecurity_getDefaultSeller
  (JNIEnv *, jclass);

/*
 * Class:     com_android_demo_jni_JNISecurity
 * Method:    getPrivateKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_android_demo_jni_JNISecurity_getPrivateKey
  (JNIEnv *, jclass);

/*
 * Class:     com_android_demo_jni_JNISecurity
 * Method:    getPublicKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_android_demo_jni_JNISecurity_getPublicKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
